addSbtPlugin("au.com.onegeek" % "sbt-dotenv" % "2.1.204")
addSbtPlugin("com.codecommit" % "sbt-github-actions" % "0.12.0")
//addSbtPlugin("com.codecommit" % "sbt-github-packages" % "0.5.3")
addSbtPlugin("com.github.sbt" % "sbt-release" % "1.0.15")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.2")
